Discordmain/integration
revertinc/revert pull request #369
Opened 2023-11-19 10:54 UTC by hrutik7

2023-11-20 04:22 UTC, hrutik7 commented
@jatinsandilya This is ready for review
lemme know if there are some update in this

2023-11-20 08:03 UTC, jatinsandilya commented
> @jatinsandilya This is ready for review lemme know if there are some update in this

@hrutik7 Thanks for the PR! 

Could you add a loom video of the OAuth + APIs on the PR description as well?

2023-11-20 11:22 UTC, hrutik7 commented
https://www.loom.com/share/61c16fc032bd4f619c098a87ee62d0ca
done !

2023-11-21 11:56 UTC, jatinsandilya requested changes

2023-11-21 11:56 UTC, jatinsandilya commented on packages/backend/index.ts
> +// import https from 'node:https';
@hrutik7 Kindly remove this commented out code.

2023-11-21 11:56 UTC, jatinsandilya commented on packages/backend/routes/index.ts
> +router.post('/discord-alert', async (req, res) => {
@hrutik7 Why has this endpoint been changed?

2023-11-21 11:56 UTC, jatinsandilya commented on packages/backend/routes/index.ts
> +router.post('/discord-alert', async (req, res) => {
This has nothing to do with the Slack / Discord integration. This endpoint is used internally. We dont need a equivalent of this for Discord.

2023-11-21 11:56 UTC, jatinsandilya commented on packages/backend/services/crm/properties.ts
> +// import { InternalServerError, NotFoundError } from '../../generated/typescript/api/resources/common';
Lets not include any commented out code in any of our PRs!

2023-11-21 11:56 UTC, jatinsandilya commented on packages/js/.env.example
> -CORE_API_BASE_URL = http://localhost:4001/
Why is this file removed?

2023-11-21 11:56 UTC, jatinsandilya commented on fern.zip
Why is this added?

2023-11-21 11:56 UTC, jatinsandilya commented on fern/api/docs/docs.yml
We don't need this file since its in `fern/docs` now

2023-11-21 11:56 UTC, jatinsandilya commented on fern/api/docs/mdx/developer-guides.mdx
We don't need this file since its in fern/docs now

2023-11-21 11:56 UTC, jatinsandilya commented on packages/client/scripts/create-ssl-certs.js
We should not be adding any new script that is not really needed. I understand you used this to have a better local setup but the same can be achieved much easier with `ngrok`and its free. Lets remove this file & `create-local-server.js` as well

2023-11-21 11:56 UTC, jatinsandilya commented on packages/client/src/home/editCredentials.tsx
> +    console.log(app,"appuser")
Remove console.log from here.

2023-11-21 11:56 UTC, jatinsandilya commented on packages/react/package.json
> +    "dependencies": {
These are not required. Please revert.

2023-11-21 11:56 UTC, jatinsandilya commented on packages/client/package.json
> +  "name": "@revertdotdev/revert-ui",
I doubt we need to make any change to this file here. Please revert or let me know what's needed for Discord Integration in this file.

2023-11-21 11:56 UTC, jatinsandilya commented on packages/backend/tsconfig.json
> +        "module": "NodeNext",
Lets revert this. If this is suggestive we can keep it in a different PR

2023-11-21 11:56 UTC, jatinsandilya commented on packages/backend/services/metadata.ts
> +                {
TODO on @jatinsandilya: Provide alternative image path.

2023-11-21 11:56 UTC, jatinsandilya commented on packages/backend/routes/v1/chat/auth.ts
> +  const discordButton = `<a href="https://discord.com/api/oauth2/authorize?client_id=1163776179002683402&permissions=8&redirect_uri=http%3A%2F%2Flocalhost%3A4001%2Fauth%2Fdiscord%2Fcallback&response_
Since this piece of code seems to only help locally. Kindly remove this from the PR.

2023-11-21 11:56 UTC, jatinsandilya commented on packages/backend/package.json
> +        "discord.js": "13.x",
Are these libraries being used in this PR? If not please remove.

2023-11-21 15:19 UTC, hrutik7 commented on .github/workflows/deploy-db-changes.yml
> -        # paths:
noted

2023-11-22 06:06 UTC, jatinsandilya commented on packages/backend/routes/v1/chat/auth.ts
> +
@hrutik7 Please remove this comment as well. Thanks!

2023-11-30 09:30 UTC, closed without merging